services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--api=true"
      - "--api.insecure=false"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gabor@gaborvilics.be"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.gaborvilics.be`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard-api.rule=Host(`traefik.gaborvilics.be`) && PathPrefix(`/api`)"
      - "traefik.http.routers.dashboard-api.service=api@internal"
      - "traefik.http.routers.dashboard-api.entrypoints=websecure"
      - "traefik.http.routers.dashboard-api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$evdz0uhy$$Q6CX9xf.vcnjbSjQoAMqh."
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik_net

  svelte-app:
    image: ghcr.io/naurid/svelteportfolio/svelte-portfolio:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte-portfolio.rule=Host(`gaborvilics.be`)"
      - "traefik.http.routers.svelte-portfolio.entrypoints=websecure"
      - "traefik.http.routers.svelte-portfolio.tls.certresolver=myresolver"
    networks:
      - traefik_net

volumes:
  letsencrypt:
networks:
  traefik_net:
    external: true
