services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "60"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    environment:
      - REPO_USER=${REPO_USER}
        # This points to the file where the secret (your PAT) is mounted
      - REPO_PASS=${PAT}
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gabor@gaborvilics.be"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      #http port
      - "80:80"
      #https port
      - "443:443"
      #webui
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  svelte-app:
    container_name: svelte-portfolio
    image: ghcr.io/naurid/svelteportfolio/svelte-portfolio:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte-portfolio.rule=Host(`gaborvilics.be`)"
      - "traefik.http.routers.svelte-portfolio.entrypoints=websecure"
      - "traefik.http.routers.svelte-portfolio.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  letsencrypt:
